### ISSUE TITLE
unhandledRejection Error: Process exited with status code: 1

### ISSUE THREAD

**Issue by Seanitzel** [funbox/harold#1]
Hi,

First of all this tool looks awesome!

For some reason i am getting a 
```
unhandledRejection Error: Process exited with status code: 1
```
Error, no matter on what project im trying to run the tool on.

My environment is Mac - Catalina.

**Comment by igoradamenko** [comment]
Hey! Thanks for sharing your experience with the tool! 

When you run `harold snapshot` Harold tries to run `NO_HASH npm run build-production`. Do you have `build-production` script in your package.json?

If you don't, you may pass any other build command using [`--exec` option](https://github.com/funbox/harold#snapshot-options).

If the issue occurs even with `--exec` option passed, would you mind to share more data? Such as project source code (when possible), package.json content, or at least logs which shows your attempts to run the tool.

_It looks like we should add sort of `--debug` option and we will probably do soon._

**Comment by Seanitzel** [comment]
Hi, My bad, that fixed it.

It works great, thanks :)
